version: '3.0'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app

    ports:
      - "8080:8080"

    networks:
      - myNetwork

  mysql-docker-container:
    image: mysql:5.7
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: householdLedger
      MYSQL_ROOT_PASSWORD: 123123
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

    networks:
      - myNetwork

networks:
  myNetwork:
